databases = {
  0: {
    name: 'Test1',
    database: 'PostgreSQL',
    projectReset: false,
    tableIndex: 1,
    databaseID: 0,
    tables: {
      0: {
        type: 'Person',
        fields: {
          0: {
            name: 'id',
            type: 'ID',
            primaryKey: true,
            autoIncrement: true,
            unique: true,
            defaultValue: '',
            required: false,
            multipleValues: false,
            relationSelected: false,
            relation: {
              tableIndex: -1,
              fieldIndex: -1,
              refType: '',
            },
            refByIndex: 0,
            refBy: {},
            tableNum: 0,
            fieldNum: 0,
          },
          1: {
            name: 'Name',
            type: 'String',
            primaryKey: false,
            autoIncrement: false,
            unique: false,
            defaultValue: '',
            required: false,
            multipleValues: false,
            relationSelected: false,
            relation: {
              tableIndex: -1,
              fieldIndex: -1,
              refType: '',
            },
            refBy: {},
            tableNum: 0,
            fieldNum: 1,
          },
          2: {
            name: 'Age',
            type: 'Number',
            primaryKey: false,
            autoIncrement: false,
            unique: false,
            defaultValue: '',
            required: false,
            multipleValues: false,
            relationSelected: false,
            relation: {
              tableIndex: -1,
              fieldIndex: -1,
              refType: '',
            },
            refBy: {},
            tableNum: 0,
            fieldNum: 2,
          },
        },
        fieldsIndex: 3,
        tableID: 0,
      },
    },
    selectedTable: {
      type: '',
      fields: {},
      fieldsIndex: 1,
      tableID: -1,
    },
    selectedField: {
      name: '',
      type: 'String',
      primaryKey: false,
      autoIncrement: false,
      unique: false,
      defaultValue: '',
      required: false,
      multipleValues: false,
      relationSelected: false,
      relation: {
        tableIndex: -1,
        fieldIndex: -1,
        refType: '',
      },
      refBy: {},
      tableNum: 0,
      fieldNum: -1,
    },
  },
};


